# items.py
# items with inflation values based off of the Bureau of Labor Statistics
# groupings and indices.  ftp://ftp.bls.gov/pub/time.series/cu/cu.item
items = {'SA0': 'All items',
         'SA0E': 'Energy',
         'SA0L1': 'All items less food',
         'SA0L12': 'All items less food and shelter',
         'SA0L12E': 'All items less food shelter and energy',
         'SA0L12E4': 'All items less food shelter energy and used cars and trucks',
         'SA0L1E': 'All items less food and energy',
         'SA0L2': 'All items less shelter',
         'SA0L5': 'All items  less medical care',
         'SA0LE': 'All items less energy',
         'SA311': 'Apparel less footwear',
         'SAA': 'Apparel',
         'SAA1': 'Men\'s and boys\' apparel',
         'SAA2':	'Women\'s and girls\' apparel',
         'SAD': 'Durables',
         'SAE': 'Education and communication',
         'SAE1': 'Education',
         'SAE2': 'Communication',
         'SAE21': 'Information and information processing',
         'SAEC': 'Education and communication commodities',
         'SAES': 'Education and communication services',
         'SAF': 'Food and beverages',
         'SAF1': 'Food',
         'SAF11': 'Food at home',
         'SAF116': 'Alcoholic beverages',
         'SAG': 'Other goods and services',
         'SAG1': 'Personal care',
         'SAGC': 'Other goods',
         'SAGS': 'Other personal services',
         'SAH':'Housing',
         'SAH1': 'Shelter',
         'SAH2':'Fuels and utilities',
         'SAH21': 'Household energy',
         'SAH3': 'Household furnishings and operations',
         'SAH31': 'Household furnishings and supplies',
         'SAM': 'Medical care',
         'SAM1': 'Medical care commodities',
         'SAM2': 'Medical care services',
         'SAR': 'Recreation',
         'SARC':'Recreation commodities',
         'SARS': 'Recreation services',
         'SAS': 'Services',
         'SAS24': 'Utilities and public transportation',
         'SAS2RS': 'Rent of shelter',
         'SAS367': 'Other services',
         'SAS4': 'Transportation services',
         'SASL2RS': 'Services less rent of shelter',
         'SASL5': 'Services less medical care services',
         'SASLE': 'Services less energy services',
         'SAT': 'Transportation',
         'SAT1': 'Private transportation',
         'SATCLTB': 'Transportation commodities less motor fuel',
         'SEAA': 'Men\'s apparel',
         'SEAB': 'Boys\' apparel',
         'SEAC': 'Women\'s apparel',
         'SEAD': 'Girls\' apparel',
         'SEAE': 'Footwear',
         'SEAF': 'Infants\' and toddlers\' apparel',
         'SEAG': 'Jewelry and watches',
         'SEEA': 'Educational books and supplies',
         'SEEB': 'Tuition other school fees and childcare',
         'SEEC': 'Postage and delivery services',
         'SEED': 'Telephone services',
         'SEEE': 'Information technology hardware and services',
         'SEEEC': 'Information technology commodities',
         'SEFV': 'Food away from home',
         'SEFW': 'Alcoholic beverages at home',
         'SEFX': 'Alcoholic beverages away from home',
         'SEGA': 'Tobacco and smoking products',
         'SEGB': 'Personal care products',
         'SEGC': 'Personal care services',
         'SEGD': 'Miscellaneous personal services',
         'SEGE': 'Miscellaneous personal goods',
         'SEHA': 'Rent of primary residence',
         'SEHB': 'Lodging away from home',
         'SEHB01': 'Housing at school excluding board',
         'SEHB02': 'Other lodging away from home including hotels and motels',
         'SEHC': 'Owners\' equivalent rent of residences',
         'SEHD': 'Tenants\' and household insurance',
         'SEHE': 'Fuel oil and other fuels',
         'SEHF': 'Energy services',
         'SEHG': 'Water and sewer and trash collection services',
         'SEHN': 'Housekeeping supplies',
         'SEMC': 'Professional services', # defined as health professionals
         'SEMD': 'Hospital and related services',
         'SEME': 'Health insurance',
         'SEMF': 'Medicinal drugs',
         'SEMG': 'Medical equipment and supplies',
         'SERA': 'Video and audio',
         'SERA01': 'Televisions',
         'SERA02': 'Cable and satellite television and radio service',
         'SERA03': 'Other video equipment',
         'SERA04': 'Video discs and other media including rental of video and audio',
         'SERA05': 'Audio equipment',
         'SERA06': 'Audio discs tapes and other media',
         'SERAC': 'Video and audio products',
         'SERAS': 'Video and audio services',
         'SERB': 'Pets pet products and services',
         'SERC': 'Sporting goods',
         'SERD': 'Photography',
         'SERE': 'Other recreational goods',
         'SERF': 'Other recreation services',
         'SERG': 'Recreational reading materials',
         'SETA': 'New and used motor vehicles',
         'SETA01': 'New vehicles',
         'SETA02': 'Used cars and trucks',
         'SETA03': 'Leased cars and trucks',
         'SETA04': 'Car and truck rental',
         'SETB': 'Motor fuel',
         'SETC': 'Motor vehicle parts and equipment',
         'SETD': 'Motor vehicle maintenance and repair',
         'SETE': 'Motor vehicle insurance',
         'SETF': 'Motor vehicle fees',
         'SETG': 'Public transportation',
         'SETG01': 'Airline fare',
         'SETG02': 'Other intercity transportation',
         'SETG03': 'Intracity transportation'}